export interface Country {
  name: string,
  toplevelDomain: [],
  alpha2Code: string,
  alpha3code: string,
  callingCodes: [],
  capital: string,
  altSpellings: [],
  region: string,
  subregion: string,
  population: number,
  latlng: [],
  demonym: string,
  area: number,
  gini: number,
  timezones: [],
  borders: [],
  nativeName: string,
  numericCode: string,
  currencies: [],
  languages: [],
  translations,
  flag: string,
  regionalBlocs: [],
  cioc: string
}
